### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by Tendies85** [Tendies85/TheWayOfGods#1]
Character with 4  numericals values

1. Health 0 - 100
The Charakter can get and lose it  during the game. 0 or less Health he died and the game restarts. He starts with 100

2. Money 0 - unlimited
The Charakter can get and lose it during the game.He can  buy things like items, food or services. He starts with 0

3. Food 0 - 25
The Character can get and lose it during the game. After every event he lose 1. When food counts 0 then he lose the game. He starts with 5

4. follower 0 - unlimited
The Character can get and lose it during the game. The follower provide information on the progress of the game.

**Comment by krysopath** [comment]
fix in #4
